Added a language layout switching button
amarula/cutekeyboard pull request #14
Opened 2024-04-24 08:02 UTC by Johannes-bichler

Hello,
This keyboard does support multiple layouts, but does not support switching between them at runtime.
For this purpose, I've implemented a button (LanguageKey), that switches between a List of Layouts that can be set via a property (availableLanguageLayouts) in InputPanel.
As this layout switching was added, the Greek Layout was changed to be similar to the others, as the internal layout switcher
(greek-latin) is no longer needed.
If this property is kept empty, it will be automatically set to En, but the property languageLayout overrides this.
If only one language is selected, the layout changer will not be visible.
If an invalid layout is added to the list property, it will fallback to "En".

2024-04-29 13:27 UTC, AndreaRicchi requested changes
Thanks for your contribution, **this is a great improvement**. Some minor comments regarding code formatting. Also, I suggest squashing the two commits for a cleaner history.

2024-04-29 13:27 UTC, AndreaRicchi commented on src/qml/CsLayout.qml
> +            weight: availableLanguageLayouts.length === 1? 217 : 108.5
This code is not formatted! Also all the other layouts.

2024-04-29 13:27 UTC, AndreaRicchi commented on src/qml/InputPanel.qml
> +            onLanguageLayoutChanged:{
Same: not formatted

2024-04-29 13:27 UTC, AndreaRicchi commented on src/qml/LanguageKey.qml
Same: not formatted

2024-04-30 07:36 UTC, Johannes-bichler commented
@AndreaRicchi How do you want this code to be formatted? Do you recommend any formatter for this purpose?

2024-04-30 07:38 UTC, panicking commented on src/qml/CsLayout.qml
> +            weight: availableLanguageLayouts.length === 1? 217 : 108.5
@Johannes-bichler I think this one from
            weight: availableLanguageLayouts.length === 1? 217 : 108.5
to
            weight: availableLanguageLayouts.length === 1 ? 217 : 108.5

2024-04-30 07:39 UTC, panicking commented on src/qml/InputPanel.qml
> +            onLanguageLayoutChanged:{
@Johannes-bichler from  Connections{ to  Connections {

2024-04-30 07:46 UTC, Johannes-bichler commented
Formatting has been completed and commits were squashed, everything should look fine now.

2024-04-30 07:47 UTC, Johannes-bichler commented on src/qml/CsLayout.qml
> +            weight: availableLanguageLayouts.length === 1? 217 : 108.5
@panicking I have used the QtCreator included QML Formatter and it worked exactly like you proposed. :grin:

2024-04-30 08:05 UTC, AndreaRicchi approved these changes

2024-04-30 08:05 UTC, AndreaRicchi commented
@Johannes-bichler you can also use the QML formatter included in the Qt SDK!

2024-04-30 08:05 UTC, merged