Feat compile with cmake
amarula/cutekeyboard pull request #9
Opened 2024-01-23 14:00 UTC by henrique-jung-isi

2024-01-23 14:18 UTC, AndreaRicchi requested changes
Thanks @henrique-jung-isi for your submission, for sure CMake support would be more than useful.

Just a couple of notes but in general looks fine.

2024-01-23 14:18 UTC, AndreaRicchi commented on src/src.pro
I suggest squashing into the other commit.

2024-01-23 14:18 UTC, AndreaRicchi commented on CMakeLists.txt
> +cmake_minimum_required(VERSION 3.21.1)
I would drop the minor here. It's too strict.
```
cmake_minimum_required(VERSION 3.21)
```

2024-01-23 14:18 UTC, AndreaRicchi commented on src/CuteKeyboard/EnterKey.qml
> +    // enabled: InputContext.focusItemHasEnterKeyAction(InputContext.inputItem) ? InputContext.inputItem.EnterKeyAction.enabled : true
Here you dropped a used feature. Cannot do that. Revert the comment line.

2024-01-23 14:18 UTC, AndreaRicchi commented on src/CuteKeyboard/InputPanel.qml
QML files where formatted using `qmllint` tool. So please do not reformat code.

2024-01-23 20:06 UTC, henrique-jung-isi commented on src/CuteKeyboard/EnterKey.qml
> +    // enabled: InputContext.focusItemHasEnterKeyAction(InputContext.inputItem) ? InputContext.inputItem.EnterKeyAction.enabled : true
Sorry about this.
I was actually trying to make a pull request on my fork, but the standard apparently is to make it on the upstream.
Since you liked it, I made the changes you requested, but this one is kind of tough. I don't know why the function is not working in the QML side of things, so i commented it out, because it was not needed for what I wanted to do.
But I did make a change: using nullish coalescing and optional chaining I think it will have the same effect as the function.

2024-01-24 13:58 UTC, AndreaRicchi commented on src/CuteKeyboard/EnterKey.qml
> +    // enabled: InputContext.focusItemHasEnterKeyAction(InputContext.inputItem) ? InputContext.inputItem.EnterKeyAction.enabled : true
Yes, I saw what you did, in this case drop the comment for the new function.

2024-01-24 13:59 UTC, AndreaRicchi commented
@henrique-jung-isi another note, please add CMake also to the example. So people can run it also using CMake! Thanks

2024-01-24 16:47 UTC, henrique-jung-isi commented
> @henrique-jung-isi another note, please add CMake also to the example. So people can run it also using CMake! Thanks

done

2024-01-24 17:03 UTC, AndreaRicchi approved these changes

2024-01-24 17:03 UTC, merged